GET http://localhost:3009/api/wanaka/player/1 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJleHAiOjE3ODg0MzIxMDMsInN1YiI6IjkyNTI1ODQwIn0.qvDip1DnZNozL2F0xcpTzC_v2qeHFAEfPubi2UZzGFM
